- name: Deploy to EC2
  hosts: localhost
  connection: local

  tasks:
    - name: Launch EC2 Instance
      amazon.aws.ec2_instance:
        instance_type: t2.medium
        image_id: ami-0230bd60aa48260c6
        region: us-east-1
        key_name: AWS-novj53
        network:
          assign_public_ip: true
        state: "running"
        wait: true
        count: 1
        security_group: eshop
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        security_token: "{{ session_token }}"
      register: ec2_instance_result

    - name: Check if instance is available with IP
      amazon.aws.ec2_instance_info:
        region: us-east-1
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        security_token: "{{ session_token }}"
        instance_ids: "{{ ec2_instance_result.instance_ids }}"
      when: ec2_instance_result.public_ip_address is defined
      register: ec2_instances

    - name: Write out item
      ansible.builtin.debug:
        msg: "{{ ec2_instances }}"

    - name: Add instance host to group
      ansible.builtin.add_host:
        hostname: "{{ item.public_ip_address }}"
        groupname: launched
      loop: "{{ ec2_instances.instances }}"

    - name: Wait for ssh connection
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection:
        delay: 30
        timeout: 300
      loop: "{{ ec2_instances.instances }}"

- name: Configure EC2
  hosts: launched
  connection: ssh

  tasks:
    - name: Install Git and Docker
      yum:
        name:
          - git
          - docker
        state: latest
        update_cache: yes
      become: yes
    - service:
        name: docker
        state: started
        enabled: yes
      become: yes
    - name: Start Docker on startup
      shell: systemctl enable docker
      become: yes
    - name: Set rights to Docker
      shell: usermod -a -G docker ec2-user
      become: yes
    - name: Get eshop from Git
      git:
        repo: 'https://github.com/novj53/4it572_semestralni_prace.git'
        dest: ./app
    - name: Build Docker with eshop
      shell: cd app && docker build -t myeshop:latest .
      become: yes
    - name: Run Docker with eshop
      shell: docker run -p 80:3000 myeshop
      async: 45
      poll: 0
      become: yes
    - wait_for:
        port:
          80
